name: Test Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib numpy scikit-learn scipy

    - name: Run tests
      run: |
        python test_driveline.py

    - name: Test script runs without errors
      run: |
        python -c "
        import driveline
        import pandas as pd
        import numpy as np
        
        # Create test data
        test_data = pd.DataFrame({
            'pitch_speed_mph': np.random.normal(90, 5, 50),
            'peak_velocity_x': np.random.normal(13, 2, 50),
            'peak_velocity_y': np.random.normal(9, 1.5, 50),
            'peak_acceleration_x': np.random.normal(50, 10, 50),
            'test_date': ['2024-01-01'] * 50,
            'athlete_uid': [f'athlete_{i}' for i in range(50)]
        })
        
        # Save test data to CSV
        test_data.to_csv('test_data.csv', index=False)
        
        # Test that main functions work
        data = driveline.load_data('test_data.csv')
        filtered_data = driveline.filter_columns(data)
        cleaned_data = driveline.handle_missing_values(filtered_data)
        X, y = driveline.prepare_features_target(cleaned_data)
        
        print('✅ Script runs successfully!')
        "
