name: Run Jupyter Notebook

on:
  push:
    paths:
      - 'driveline.ipynb'
      - '.github/workflows/run-notebook.yml'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'driveline.ipynb'
      - '.github/workflows/run-notebook.yml'
      - 'requirements.txt'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert ipykernel

      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute driveline.ipynb --output executed_driveline.ipynb --ExecutePreprocessor.timeout=600
